import 'dart:convert';
import 'model.dart';
import 'package:http/http.dart' as http;

class ApiService {
  final String apiUrl =
      'https://newsapi.org/v2/everything?q=bitcoin&apiKey=94a3c5b468ea4110b897ee5eb0e41e61';

  Future<Autogenerated?> getAllArticles() async {
    try {
      final response = await http.get(Uri.parse(apiUrl));

      if (response.statusCode == 200) {
        return Autogenerated.fromJson(jsonDecode(response.body));
      } else {
        print('Failed to load articles, status code: ${response.statusCode}');
        return null;
      }
    } catch (e) {
      print('Error fetching articles: $e');
      return null;
    }
  }
}
